server:
  port: 8765
spring:
  application:
    name: feign-service
eureka:
  client:
    service-url:
      default-zone: localhost:8761/eureka/  
      
#fegin自带断路器，默认为关闭，需手动打开
feign:
  hystrix:
    enabled: true 
