eureka:
  instance:
    #使用ip进行配置
    prefer-ip-address: true 
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul-server
zuul:
  routes:
    ribbonservice:
      path: /ribbon/**
      service-id: ribbon-service
    feignservice:
      path: /feign/**
      service-id: feign-service
    
